#pragma once

enum typeOfMatrix {COMMONTYPE, SQUARE, UNITARY, ORTHOGONAL, UPTRIANGLE, DOWNTRIANGLE, NULLMATRIX, DIAGONAL};

enum Errors { FILENOTFOUND, INCORRECTCELL, DIFFERENTSIZES, IMPOSSIBLEMATRIXMULTIPLUCATION, NOTSQUARENODETERMINER, WRONGINITIALIZATIONSIZE};